### ISSUE TITLE
Bitwise operations with cenum drop type information

### ISSUE THREAD

**Issue by sairus7** [JuliaInterop/CEnum.jl#13]
This leads to errors in ccall function signatures with enum types in its arguments:
```
julia> using CEnum

julia> @cenum(Bar, d = 1, e = 2, f = 1)

julia> foo = d
d::Bar = 1

julia> foo = d | e  # <-- not a Bar type !
3

julia> foo = Bar(d | e)   # <-- unless we convert to Bar
UnknownMember::Bar = 3
```

One possible solution would be adding binary (and maybe arithmetic?) methods into @cenum macro. However, I get this error:
```
julia> Base.|(x::Bar, y::Bar) = Bar(x | y)
ERROR: syntax: invalid argument destructuring syntax "(x::Bar, y::Bar)"
```

**Comment by sairus7** [comment]
Link to the actual error:
https://github.com/wsphillips/ImPlot.jl/issues/11#issuecomment-803127648

**Comment by Gnimuc** [comment]
This is the correct and expected C/C++ behavior, see https://stackoverflow.com/a/1448404/4594532

**Comment by Gnimuc** [comment]
and to overload | operator, you need to use :|

**Comment by sairus7** [comment]
Thanks, this works: `Base.:|(x::Bar, y::Bar) = Bar(Int(x)|Int(y))`

But if that is correct behaviour, then there is another error in api wrapper.
Oh, the real issue is that flags are not enums but `typedef int`: https://github.com/epezent/implot/blob/master/implot.h#L56
So, this is about Clang.jl proper deducing typedefs or converting them into Julian `const`?

**Comment by Gnimuc** [comment]
> So, this is about Clang.jl proper deducing typedefs or converting them
into Julian const?

sorry, i don’t quite understand what you mean here. if a type Foo is
defined as a int via a typedef int Foo, then the code generated by Clang.jl
should be const Foo = Cint.

btw, if you’d like to overload | operator for cenums, you’re free to
overload it in your own package.

2021年3月20日(土) 9:45 Viktor G. Gumennyy ***@***.***>:

**Comment by sairus7** [comment]
From the example linked above, I want to write in Julia:
`flags = ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_NoTickMarks`
and then call this method properly: https://github.com/wsphillips/ImPlot.jl/blob/master/src/libcimplot/libcimplot_api.jl#L26

For now, it only works if I write like this:
`flags = ImPlotAxisFlags(ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_NoTickMarks)`

**Comment by Gnimuc** [comment]
Could you confirm [this code](https://github.com/wsphillips/ImPlot.jl/blob/bcf838585f4d8a6462c7dc1dcdb9eb2b98ab2616/src/libcimplot/libcimplot_common.jl#L27-L39) is generated by Clang.jl?

**Comment by sairus7** [comment]
No I can't, but maybe @wsphillips can?

**Comment by Gnimuc** [comment]
I believe the code that Clang.jl generated was:
```
const ImPlotAxisFlags = Cint

@cenum ImPlotAxisFlags_::Cint begin
    ImPlotAxisFlags_None            = 0
    ...
    ...
end
```
but @wsphillips did some additional tweaks, which eventually cause the problem.

**Comment by Gnimuc** [comment]
Anyway, this is not an issue of CEnum.jl, let's continue the discussion in CImplot.jl.
