### ISSUE TITLE
Check for overflow is incorrect

### ISSUE THREAD

**Issue by jlapeyre** [JuliaInterop/CEnum.jl#18]
I think this
https://github.com/JuliaInterop/CEnum.jl/blob/433d4ec1cae51c1bd6b8ff4f4085048ca4a44e92/src/CEnum.jl#L128

may be incorrect. Shouldn't this be
```julia
x ≤ typemax($basetype)
```
For example `x` may be `Int64`, and you want to check whether it overflows when converted to `Int32`.

Furthermore, negative numbers are allowed. So underflow should be checked too: `x ≤ typemax($basetype) && x >= typemin($basetype)`.

**Comment by Gnimuc** [comment]
Should we remove that line? It is used for checking membership in the implementation of Julia's `@enum`:

https://github.com/JuliaLang/julia/blob/ab261919071c97cb70d880270453c43b6474b7e8/base/Enums.jl#L205

It's legal in C to cast a non-member enum value to be a enum type:

```
julia> using CEnum

julia> @cenum Foo begin
           x = 1;
           y = 2;
       end

julia> Foo(x|y)
UnknownMember::Foo = 3

julia> @enum Bar begin
           xx = 1;
           yy = 2;
       end

julia> Bar(3)
ERROR: ArgumentError: invalid value for Enum Bar: 3
Stacktrace:
 [1] enum_argument_error(typename::Symbol, x::Int64)
   @ Base.Enums .\Enums.jl:85
```

**Comment by Gnimuc** [comment]
In the next line, `convert` will check overflow issues for us:
```
return bitcast($(esc(typename)), convert($(basetype), x))
```

**Comment by jlapeyre** [comment]
Just to be clear, there are two issues (If I understand, you also see the same issues.)

* Yes, the line `return bitcast...` does throw an error. The error message shown by `enum_argument_error` is arguably worse because it does not give information on why the value is not valid. But, it does give more context, ie mentions `Enum Bar`.
* The test  `x ≤ typemax(x)` is always true, so `enum_argument_error` will never be called here. In other words, this line is a no-op.

So the line has to be changed. The question is whether to fix it or remove it. Removing it simplifies the code. If the line remains, I would argue that it should check for both overflow and underflow, and that the error message be more informative. Otherwise it is not very useful.

**Comment by Gnimuc** [comment]
I'm going to remove that line because it doesn't change the behavior of the current program (in the case of overflow, it throws an `InexactError`, but if we add a new error message, we may break some test cases in the down-stream packages that check against this particular error type).
