### ISSUE TITLE
Bitwise ~ not working

### ISSUE THREAD

**Issue by wsphillips** [JuliaInterop/CEnum.jl#9]
Bitwise comparisons of enumerations works for `|` and `&` but not for `~`. This causes an issue for certain C-style flag comparisons/definitions:

```julia
@cenum FooFlags begin
A = 1 << 0
B = 1 << 1
C = 1 << 2
D = 1 << 3
end
const DEFAULTS = A | B | C # works
const ALT_DEFAULTS_2 = DEFAULTS & ~C # fails; no method for ~ for type FooFlags  
```

**Comment by Gnimuc** [comment]
I missed that unary operator in [operators.jl](https://github.com/JuliaInterop/CEnum.jl/blob/master/src/operators.jl). Would you like to make a PR?
